// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    CreateModal: typeof import('./src/components/CreateModal.vue')['default']
    CreateTask: typeof import('./src/components/CreateTask.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TasksList: typeof import('./src/components/TasksList.vue')['default']
  }
}
